### ISSUE TITLE
Use template magic to replace macroes

### ISSUE THREAD

**Issue by obfuscate** [bsviglo/ECS_experiments#5]
Wishes:
- [x]  Avoid using of macroes to hide RTTR registration code.
- [x]  Add an opprotunity to register properties of a class.

**Comment by obfuscate** [comment]
@mrduda можешь посмотреть коммит fb97811af17bd9269c409318b375518365e3820b? Может будут какие-нибудь предложения как можно сделать лучше.

**Comment by mrduda** [comment]
В идеале привести запись вида

> RegisterComponent
> {
> 	{ "paramA", offsetOf(&TestComponent::Cfg::paramA), Property::Control::DragInt, b2Vec3(1, 0, 10) },
> 	{ "paramB", offsetOf(&TestComponent::Cfg::paramB), Property::Control::DragFloat, b2Vec3(0.1f, -10.0f, 10.0f) },
> 	{ "paramC", offsetOf(&TestComponent::Cfg::paramC), Property::Control::DragFloat, b2Vec3(0.5f, 0.0f, 33.0f) }
> }.registerWithAutoProvider<TestComponent, int, float, float>("TestComponent");
> 

К виду

> RegisterComponent<TestComponent::Cfg>( )
> 	.property("paramA", &TestComponent::Cfg::paramA, Property::Control::DragInt, b2Vec3(1, 0, 10))
> 	.property("paramB", &TestComponent::Cfg::paramB, Property::Control::DragFloat, b2Vec3(0.1f, -10.0f, 10.0f))
> 	.property("paramC", &sf::Color::paramC, Property::Control::DragFloat, b2Vec3(0.5f, 0.0f, 33.0f))
> 	.provider<TestComponentProvider>();
> 

где property - темплейтные методы RegisterComponent<TestComponent::Cfg>, разворачивающиеся в прямые вызовы rttr::registration::class_<TestComponent::Cfg>::property

**Comment by obfuscate** [comment]
Я в самом начале пытался это сделать, там какая-то шляпа с возвращаемым значениями самого rttr. Оно возвращает какое-то хитрое rttr::bind(куча параметров) для каждого проперти, которое у меня не получилось скомпилить для каждого параметра шаблона.

**Comment by mrduda** [comment]
Вышеописанное изменение сделано в бранче template_magic_denis, пока закрою текущий issue.
